### PR TITLE
[JAXRS] build API jar against final release, fix contract, build first

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @csierra once(if) you apply this please also publish a snapshot of the jar to the apache snapshots repo:

```
cd javax-ws-rs/
mvn deploy
```
Once that is done, I can update the OSGi build to use that API to compile the osgi.jaxrs API against it and get the proper contract configuration.

Then I will send the next PR which has all the rest of my fixes for several other isses.

thx!

**Comment by rotty3000** [comment]
Note, this change will very likely break the build if you try to re-resolve things. This is actually one of the issues I'm fixing.

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Merged... thx you! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
