### PR TITLE
de-bounce the changecount by allowing batching of multiple changes

### PR DESCRIPTION
**Pull request by rotty3000**
what do you think of this change, see the commit comment!

### CODE REVIEW

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @rotty3000, 
I would rather keep that logic outside the registrator because, when we implement error handling, it might be the case that we need to bail out of `rewire` because of an exception but we still to update the error count because we are publishing an error of some sort. 
Maybe I was too sloppy when I set the count where I set it but maybe we can find a place deeper in the _"OSGi program"_ that does not bounce that much and still keeps the registrator clear from that side effect.
What do you think?

**Comment by rotty3000** [comment]
That's a good point! I'll re-work my other changes. Note, we still need to
pass around a much more complete context to the registrator anyway. But I
will leave the count out for now.

**Comment by rotty3000** [comment]
couldn't you simply use this new object during error handling while still keeping this impl the way it is?

**Pull request closed without merging**
